- week6/leetcode/1598-crawler-log-folder/itsmo1031.java
- week6/programmers/150365-미로-탈출-명령어/itsmo1031.java
> Runtime: 1ms
> Memory: 42.02MB
현재 폴더 명령어 빼고 이전 폴더랑 특정 폴더 이동 때마다 step을 증감시켜가며 계산했습니다. Stack을 써도 됐는데 굳이 쓸 필요성을 느끼진 못했어요.
---
> Runtime: 0.03ms
> Memory: 68.5MB
갈 방향을 알파벳 순으로 미리 정렬(D, L, R, U순)한 후 백트래킹을 사용하여 풀이했습니다.
> [정필모] 2024-07-10 풀이 제출

- week7/leetcode/2196-create-binary-tree-from-descriptions/kimgiraffe.java
- week7/programmers/17687-N진수-게임/kimgiraffe.java
> Runtime: 63ms
> Memory: 56.7MB
map을 이용하여 Tree에 대한 정보를 추적하고, set을 이용하여 children에 대한 정보를 추적하였습니다.
---
> Runtime: 27.42ms
> Memory: 79.5MB
Java의 Integer.toString(int i, int radix) method를 이용하여 진법 변환하였습니다.
[참고](https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html)
> [김세민] 240715

- week7/leetcode/2196-create-binary-tree-from-descriptions/itsmo1031.java
- week7/programmers/17687-N진수-게임/itsmo1031.java
> Runtime: 59ms
> Memory: 56.5MB
TreeNode 자체에 parent가 없어서 TreeNode를 확장할까 하다가 그냥 HashMap을 활용해서 풀이했습니다. 메모리 사용률이 다른 사람들보다 1~2MB가량 높은데 메서드를 따로 빼서 그런건지는 모르겠습니다.
---
> Runtime: 12.42ms
> Memory: 81.3MB
Integer 클래스의 toString을 활용해서 풀이했는데, 만약 C++이나 파이썬 등 진법 변환을 지원하지 않는 다른 언어를 사용할 경우 어떻게 풀이해야 깔끔할지 감이 잘 잡히지 않네요. 좋은 아이디어 있으면 의견 부탁드립니다.
> [정필모] 240715 풀이 제출

- week7/leetcode/2196-create-binary-tree-from-descriptions/rglley.java
- week7/programmers/17687-N진수-게임/rglley.java
> Runtime: 65ms
> Memory: 55.33MB
입력값에 따라 노드를 생성해 HashMap에 저장, 자식 노드값을 Set에 저장
RootNode 값을 찾아(Set에 미포함) HashMap에서 꺼내 반환
---
> Runtime: 17.82ms
> Memory: 77.6MB
- [] ✅ 막힘 없이 풀었어요.
인원수, 단어 개수 최대 길이만큼 N진수로 변환해 저장
차례에 해당하는 Index의 char들을 StringBuilder로 append 후 반환
> [이경배] 2024. 07. 15. 풀이 제출 

- week7/leetcode/2096-step-by-step-directions-from-a-binary-tree-node-to-another/kimgiraffe.java
- week7/programmers/60062-외벽-점검/kimgiraffe.java
> Runtime: 19ms
> Memory: 79.9MB
DFS로 시작 노드와 도착 노드를 각각 탐색하여 공통 부분을 찾고, 나머지 부분은 StringBuilder를 이용하여 처리하였습니다.
---
> Runtime: 73.8ms
> Memory: 63.25MB
원형 구조를 직선 형태로 변형하고, 순열을 이용하여 필요한 친구 수를 갱신하였습니다.
> [김세민] 240716 풀이 제출

- week7/leetcode/2096-step-by-step-directions-from-a-binary-tree-node-to-another/itsmo1031.java
- week7/programmers/60062-외벽-점검/itsmo1031.java
> Runtime: 24ms
> Memory: 78.87MB
LCA 문제임은 짐작하고 있었지만, 주어지는 값이 root노드이고 이를 어떻게 활용해서 LCA를 찾아야 할지 감을 전혀 못잡아서 오랜 고민 후 Editorial을 보고 학습했습니다. 재귀에 대한 직관적인 이해가 아직 부족한 것 같네요.
---
> Runtime: 37.34ms
> Memory: 82.4MB
원형으로 이루어진 벽을 배열의 길이를 2배로 늘려 방향을 신경쓰지 않도록 만들었습니다. 이후 순열을 이용하여 최대 효율을 계산하도록 풀이했어요. 사실 이전에 파이썬으로 푼 기억이 있어서 쉽게 접근했네요. 다만 자주 사용하던 Next Permutation에 대한 구현부를 잊어버려 다시 공부했습니다. 알고리즘 노트를 만들어서 정리를 해야겠다는 생각을 했습니다.
> [정필모] 240716 풀이 제출

- week7/leetcode/1110-delete-nodes-and-return-forest/kimgiraffe.java
- week7/programmers/92335-k진수에서-소수-개수-구하기/kimgiraffe.java
> Runtime: 0ms
> Memory: 44.38MB
삭제할 노드 여부를 저장할 1차원 배열을 선언하고, 후위순회를 진행하였습니다.
현재 노드가 root인지 여부를 저장할 `flag` 변수를 선언하였습니다.
재귀 호출 이후, 현재 노드가 삭제할 노드가 아니고, `flag`가 `true` 라면, 새로운 `tree`의 root 노드이므로 `answer`에 추가합니다.
---
> Runtime: 16.91ms
> Memory: 64.7MB
k진수로 변환 후 `"0"` 기준으로 문자열을 자릅니다. 
자른 문자열을 `long` 자료형으로 변환하고 소수 판별하였습니다.
> [김세민] 240717 풀이 제출

- week7/leetcode/2096-step-by-step-directions-from-a-binary-tree-node-to-another/rglley.java
- week7/programmers/60062-외벽-점검/rglley.java
> Runtime: 24ms
> Memory: 69.2MB
DFS 풀이 Runtime이 너무 길어 BFS 풀이법을 참고했습니다.
가장 낮은 공통 조상을 찾아 공통 조상을 기준으로 Start, Dest 노드로 탐색을 진행해 경로를 저장했습니다.
---
> Runtime: 62.37ms
> Memory: 85MB
완전 탐색으로 모든 경우(취약 부분, 투입 순서)를 직접 생성하는 풀이를 참고했습니다.
취약부분을 원형 기준점에 따라 다르게 표기하는 점이 포인트였던 것 같습니다.
> [이경배] 240716 풀이 제출

- week7/leetcode/1110-delete-nodes-and-return-forest/itsmo1031.java
- week7/programmers/92335-k진수에서-소수-개수-구하기/itsmo1031.java
> Runtime: 1ms
> Memory: 44.6MB
후위 순회를 이용해 제일 하단 노드부터 탐색했습니다. DFS의 재귀가 참 머리아팠네요... 익숙해져야겠다는 생각이 들었습니다.
---
> Runtime: 14.66ms
> Memory: 75.1MB
진법 변환 후 0을 기준으로 문자열을 잘라 각각 소수임을 판별하는 방식으로 풀이했습니다. 처음에 복잡도를 줄이려고 에라토스테네스의 체를 이용하려 했는데 생각해보니 이러면 잘린 문자열의 최댓값 기준으로 만들어야하기도 하고, 이게 int범위를 넘어버릴 가능성도 있길래 그냥 각각 확인하는 방식으로 변경해서 풀이했어요.
> [정필모] 240717 문제 풀이 제출

- week7/leetcode/1530-number-of-good-leaf-nodes-pairs/kimgiraffe.java
- week7/programmers/77886-110-옮기기/kimgiraffe.java
> Runtime: 25ms
> Memory: 45MB
재귀로 각 부모 노드로부터의 거리를 구하고, 
부모 노드로부터의 거리의 합이 `distance` 가 되는 leaf node의 개수를 구했습니다.
---
> Runtime: 120.38ms
> Memory: 105MB
문자열에서 "110" 을 찾아 뽑은 후 `StringBuilder`에 append 하였습니다.
"110"을 모두 뽑고 남은 문자열에서 "0"이 있다면, 마지막 "0"이 등장하는 다음 위치에 뽑은 "110"을 삽입하고,
"0"이 없다면, 맨 앞에 "110"을 삽입하였습니다.
> [김세민] 240718 문제 풀이 제출

- week7/leetcode/1110-delete-nodes-and-return-forest/rglley.java
- week7/programmers/92335-k진수에서-소수-개수-구하기/rglley.java
> Runtime: 1ms
> Memory: 44.66MB
삭제 노드 번호를 Set에 담아 Root노드부터 쭉 순회하며 
left, right의 삭제 대상 null처리와 미삭제 대상 리스트 추가를 진행했습니다.
---
> Runtime: 11.54ms
> Memory: 75MB
k진수로 변환한 후 0(연속된 0)을 기준으로 split해 배열에 담아 소수 여부를 판단했습니다.
> [이경배] 240717 문제 풀이 제출

- week7/leetcode/1530-number-of-good-leaf-nodes-pairs/itsmo1031.java
- week7/programmers/77886-110-옮기기/itsmo1031.java
> Runtime: 2ms
> Memory: 44.56MB
DFS를 활용해서 후위 순회하며 가장 끝단 노드부터 거리를 계산해 하나씩 쌓아 올리는 방식으로 풀이하였습니다. 재귀 문제를 한 서른개정도 더 풀어봐야 익숙해질 것 같아요...
---
> Runtime: 99.02ms
> Memory: 131MB
그리디하게 모든 110을 제거하고, 110이 사전 순으로 가장 앞에 오는 경우는 0보다 뒤에 위치하는 경우 뿐이므로 해당 위치를 찾아 모든 110을 붙여주는 방식으로 풀이했습니다. 마지막에 1을 찾지 못했을 때 110을 맨 뒤에 붙여줘야 했는데 그걸 하지 않아서 30분을 헤맸네요...
> [정필모] 240718 풀이 제출

- week7/leetcode/1380-lucky-numbers-in-a-matrix/kimgiraffe.java
- week7/programmers/17684-압축/kimgiraffe.java
> Runtime: 3ms
> Memory: 45.21MB
두 개의 List에 각 행의 최소값과 각 열의 최대값을 찾아서 저장합니다.
두 개의 List에 모두 존재하는 원소를 반환합니다.
---
> Runtime: 31.41ms
> Memory: 81.4MB
사전은 Map 자료구조를 이용했습니다.
사전에 등록된 가장 긴 문자열을 찾고, 남은 문자가 있는 경우 다음 문자를 더해 사전에 등록했습니다.
> [김세민] 240719 풀이 제출

- week7/leetcode/1530-number-of-good-leaf-nodes-pairs/rglley.java
- week7/programmers/77886-110-옮기기/rglley.java
> Runtime: 2ms
> Memory: 44.73MB
거리 별 노드 수를 저장하는 배열을 만들고,
DFS 탐색을 통해 왼쪽, 오른쪽 서브 트리의 적합한 쌍을 구해 풀이했습니다.
---
> Runtime: 80.78ms
> Memory: 133MB
"111" index를 찾아 "110"을 삽입했더니 시간 초과가 났습니다.
더 빠른 풀이를 위해 "110"을 모두 추출하고, 마지막 0인덱스 뒤로 붙여줬습니다.
> [이경배] 240718 풀이 제출

- week8/leetcode/2418-sort-the-people/kimgiraffe.java
- week8/programmers/17686-파일명-정렬/kimgiraffe.java
> Runtime: 7ms
> Memory: 45.4MB
이름과 키를  갖는 Person 객체 배열을 생성하고, 키를 기준으로 내림차순 정렬하였습니다.
---
> Runtime: 34.83ms
> Memory: 95.2MB
원래 파일명, HEAD, NUMBER를 갖는 File 객체 배열을 생성하고, 주어진 조건에 따라 정렬하였습니다.
숫자인지 여부에 따라 각각 HEAD, NUMBER로 추가하고 대소문자 구분하지 않으므로 소문자로 통일하였습니다.
> [김세민] 240722 풀이 제출

- week7/leetcode/1380-lucky-numbers-in-a-matrix/rglley.java
- week7/programmers/17684-압축/rglley.java
> Runtime: 2ms
> Memory: 44.9MB
이중 for문으로 min값을 구하고, 해당 col의 최댓값인지 확인했습니다.
---
> Runtime: 12.73ms
> Memory: 81.4MB
HashMap으로 dictionary를 생성하고,
한글자씩 늘리며 dictionary에 포함되어 있는지 확인하며 풀이했습니다.
> [이경배] 240719 풀이 제출

- week8/leetcode/2418-sort-the-people/itsmo1031.java
- week8/programmers/17686-파일명-정렬/itsmo1031.java
> Runtime: 7ms
> Memory: 45.13MB
PriorityQueue를 사용해서 풀었습니다.
---
> Runtime: 20.64ms
> Memory: 76.2MB
Comparable한 class를 만들어 정렬했습니다. 다 풀고나서 보니까 그냥 Comparator를 람다로 구현해서 풀이하는게 더 깔끔했을 것 같다는 생각이 드네요. 람다를 사용해 풀이하는 것보다 class를 만들어 사용하는 것을 선호하는 편이라 이렇게 했는데, 람다를 많이 사용해서 익숙해져야겠다는 생각을 했습니다.
> [정필모] 240722 풀이 제출

- week8/leetcode/1636-sort-array-by-increasing-frequency/itsmo1031.java
- week8/programmers/150367-표현-가능한-이진트리/itsmo1031.java
> Runtime: 6ms
> Memory: 44.37MB
HashMap에 frequency를 더해가며 수를 쌓고, frequency 오름차순, 동일 값일 시 값 내림차순으로 정렬하여 다시 array에 담아 리턴했습니다.
---
> Runtime: 21.12ms
> Memory: 89.9MB
처음에 문제를 이해하는데 시간이 걸렸습니다. 특히 `이진트리에서 리프 노드가 아닌 노드는 자신의 왼쪽 자식이 루트인 서브트리의 노드들보다 오른쪽에 있으며, 자신의 오른쪽 자식이 루트인 서브트리의 노드들보다 왼쪽에 있다고 가정합니다.`라는 부분이 당최 이해가 가질 않아서 찾아보니 중위순회를 어렵게 설명한 것이더라구요...
각설하고 로직을 설명하면 우선 주어진 숫자를 2진수로 변환하고, 이를 완전 이진 트리로 변환하는 과정을 수행했습니다. 이후 후위 순회를 통해 왼쪽, 오른쪽 트리의 존재 가능 여부를 파악합니다. 존재할 수 없는 조건은 양쪽 자식 노드가 더미 노드가 아닐 때 부모 노드가 0일 시 트리 자체가 성립하지 않습니다.
static 변수를 선언해서 존재 불가능한 트리를 발견했을 때 early return을 하도록 설정했는데, 더 나은 방법이 있을지 모르겠네요.
> [정필모] 20240723 풀이 제출

- week8/leetcode/1636-sort-array-by-increasing-frequency/kimgiraffe.java
- week8/programmers/150367-표현-가능한-이진트리/kimgiraffe.java
> Runtime: 6ms
> Memory: 44.3MB
`frquency`와 `value`를 갖는 객체 배열을 생성하고 빈도 수 와 값을 기준으로 정렬하였습니다.
빈도 수 가 0보다 큰 경우일 때까지 value를 answe 배열에 담아 반환했습니다.
---
> Runtime: 29.89ms
> Memory: 108MB
포화 이진트리 개념을 잘 몰라서 문제를 이해하는데 시간이 꽤 걸렸습니다.
이진수로 변환하고 포화 이진트리를 생성한 후, 각 트리가 하나의 이진트리로 표현 가능한지 분할정복으로 판단했습니다.
> [김세민] 240723 풀이 제출

- week8/leetcode/2418-sort-the-people/rglley.java
- week8/programmers/17686-파일명-정렬/rglley.java
> Runtime: 7ms
> Memory: 45.47MB
Info클래스(이름, 키)를 정의해 배열에 담아 키 순서로 정렬해 풀이했습니다.
---
> Runtime: 27.51ms
> Memory: 83MB
1. Name 클래스를 정의해 파일명을 head, number, tail로 분리한 후 저장했습니다.
2. Name배열을 주어진 조건대로 정렬했습니다.
> [이경배] 240722 풀이 제출

- week8/leetcode/2191-sort-the-jumbled-numbers/itsmo1031.java
- week8/programmers/17679-프렌즈4블록/itsmo1031.java
> Runtime: 152ms
> Memory: 54.8MB
Num 클래스를 만들어서 기본 num이랑 변형된 num을 같이 담아두고 이를 비교했는데, 생각해보니 굳이 클래스까지 만들지 않아도 됐을 것 같네요. 그래도 깔끔하니까 한잔해
---
> Runtime: 14.02ms
> Memory: 81.5MB
이 문제도 예전에 파이썬으로 풀 때 풀었던 문제네요. 딱히 크게 설명할 게 없는 전형적인 시뮬레이션 문제였습니다. 그러나 중복좌표를 거르기 위해 사용한 Set 때문에 시간이 좀 걸렸네요. equals랑 hashcode 재정의때문에... 아마 다시 푼다면 굳이 재정의하지 않고 r과 c를 한 숫자로 표현해서 처리하는 방식을 사용할 것 같습니다. (2<=n, m<=30이기 때문에 r에 100정도를 곱해서 c와 더해주면 쉽게 쓸 수 있을 것 같아요.)
> [정필모] 20240724 풀이 제출

- week8/leetcode/2191-sort-the-jumbled-numbers/kimgiraffe.java
- week8/programmers/17679-프렌즈4블록/kimgiraffe.java
> Runtime: 282ms
> Memory: 55.5MB
기존 숫자와 mapping된 숫자를 갖는 Pair 객체를 우선순위큐에 담고 하나씩 꺼냈습니다.
---
> Runtime: 17.5ms
> Memory: 83.7MB
제거할 블록을 찾아 List에 저장하고 map에서 제거하였습니다.
제거한 후에는 다시 블록을 아래로 채우고 더 이상 제거할 블록이 없을 때까지 위 과정을 반복했습니다.
마지막으로, 제거된 블록을 모두 찾아 개수를 반환했습니다.
> [김세민] 240724 풀이 제출

- week8/leetcode/912-sort-an-array/kimgiraffe.java
- week8/programmers/70130-스타-수열/kimgiraffe.java
> Runtime: 69ms
> Memory: 55.1MB
병합 정렬으로 구현했습니다.
---
> Runtime: 52.97ms
> Memory: 117MB
숫자별 빈도수를 배열에 저장하고, 주어진 조건을 만족하는 부분 수열의 개수를 구했습니다.
> [김세민] 240725 풀이 제출

- week8/leetcode/1334-find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/kimgiraffe.java
- week8/programmers/77885-2개-이하로-다른-비트/kimgiraffe.java
> Runtime: 11ms
> Memory: 44.5MB
플로이드 워셜 알고리즘을 이용하여 각 도시에서 모든 도시까지의 최단거리를 구한후,
`distanceThreshold` 이하의 도시 수를 구했습니다.
---
> Runtime: 3.96ms
> Memory: 103MB
`XOR`연산으로 두 수에서 같은 위치의 서로 다른 두 비트가 있는지 확인하고, 
`>>` 연산으로 가장 작은 두 개의 비트를 제거했습니다.
> [김세민] 240726 풀이 제출

- week8/leetcode/912-sort-an-array/itsmo1031.java
- week8/programmers/70130-스타-수열/itsmo1031.java
> Runtime: 26ms
> Memory: 55.6MB
Merge Sort를 활용해서 풀었습니다. 더 좋은 효율을 가진 정렬이 있을 것 같네요. 정렬 자체를 구현하는 문제는 학부생때 알고리즘 수업 이후로 처음이라 공부 후 풀었습니다...^_^
---
> Runtime: 185.25ms
> Memory: 151MB
부분 수열에 대한 설명 부분을 대충 읽고 순서가 없다고 생각해서 감을 도저히 못 잡았습니다. 문제의 갈피를 잡을 수 있는 힌트를 본 후, 현재 인덱스에 있는 배열 요소의 앞 뒤 요소와 비교하여 기준을 충족할 경우 map에 카운트를 추가해서 최댓값을 갱신시키는 방식으로 풀이했습니다.
> [정필모] 240725 풀이 제출

- week9/leetcode/1395-count-number-of-teams/kimgiraffe.java
- week9/programmers/68936-쿼드압축-후-개수-세기/kimgiraffe.java
> Runtime: 1976ms
> Memory: 42.1MB
n이 최대 1,000이라 브루트 포스로 O(n³) 의 시간 복잡도를 갖는 코드로 해결했습니다.
---
> Runtime: 8.47ms
> Memory: 128MB
분할 정복 알고리즘을 이용하여 압축이 가능한 경우, 압축하고, 그렇지 않은 경우, 4개의 영역으로 쪼개는 과정을 반복했습니다.
> [김세민] 240729 풀이 제출

- week8/leetcode/1334-find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/rglley.java
- week8/programmers/77885-2개-이하로-다른-비트/rglley.java
> Runtime: 9ms
> Memory: 44.22MB
플로이드 워셜을 사용해 풀이했습니다.
---
> Runtime: 106.31ms
> Memory: 131MB
짝수면 +1, 홀수면 마지막 0을 10(0이 없다면 처음 1을 10)으로 변환해주는 규칙을 찾아 풀이했습니다.
비트 연산자를 몰라 String으로  처리를 했더니 런타임이 상당히 기네요 🤔
> [이경배] 240726 풀이 제출

- week8/leetcode/2191-sort-the-jumbled-numbers/rglley.java
- week8/programmers/17679-프렌즈4블록/rglley.java
> Runtime: ##ms
> Memory: ##.##MB
HashMap에 mapping 결과를 담아놓고, PriorityQueue를 이용해 정렬했습니다.
그런데 num 길이가 길어서 그런지 실행 시간이 너무 길어 개선이 필요합니다 ㅠㅠ.
---
> Runtime: 20.4ms
> Memory: 87.1MB
삭제될 블럭들을 boolean배열에 저장해놓고, 삭제와 떨어지는 것을 반복해 풀이했습니다.
구현이라 그렇다할 풀이는 없었던 것 같아요,
> [이경배] 240724 풀이 제출

- week9/leetcode/1395-count-number-of-teams/rglley.java
- week9/programmers/68936-쿼드압축-후-개수-세기/rglley.java
> Runtime: 15ms
> Memory: 41.80MB
DFS 풀이가 시간 초과가 나서,
기준점을 잡고 왼쪽과 오른쪽에서 큰 수, 작은 수의 개수를 세 풀이했습니다.
---
> Runtime: 9.11ms
> Memory: 123MB
분할된 범위 내의 값이 모두 같은지 확인하는 메서드와
사이즈를 반으로 줄여가며 분할하는 재귀 메서드를 짜 풀이했습니다.
> [이경배] 240729 풀이 제출

- week9/leetcode/1653-minimum-deletions-to-make-string-balanced/kimgiraffe.java
- week9/programmers/118669-등산코스-정하기/kimgiraffe.java
> Runtime: 18ms
> Memory: 45MB
문자열을 탐색하면서 'b' 를 만난 경우, `count` 값을 1 증가시키고, 
'a'를 만나고 `count` 가 0보다 큰 경우, 삭제해야 하는 횟수를 1 증가시키고, `count` 값은 1 감소시켰습니다.
---
> Runtime: 2055.64ms
> Memory: 159MB
출입구에 연결된 양방향 등산로 -> 출입구에서 다른 지점으로만 이동 가능한 단방향 등산로
산봉우리 연결된 양방향 등산로 -> 다른 지점에서 산봉우리로만 이동 가능한 단방향 등산로
경로의 가중치는 단조증가하기 때문에, dijkstra 알고리즘의 최단거리 배열 갱신 방법에서 약간 변형하여 intensity 갱신하였습니다.
https://tech.kakao.com/posts/530
> [김세민] 240730 풀이 제출

- week9/leetcode/1105-filling-bookcase-shelves/kimgiraffe.java
- week9/programmers/68645-삼각-달팽이/kimgiraffe.java
> Runtime: 0ms
> Memory: 41.8MB
dp 로 하나씩 기존 선반에 현재 책을 추가하면 선반의 너비를 초과하는지 확인합니다. 그렇지 않은 경우 선반의 높이는 해당 선반에 이미 있는 가장 높은 책에 의해 결정됩니다.
---
> Runtime: 49.83ms
> Memory: 156MB
너비 우선 탐색을 이용하여 이차원 배열에 숫자를 채워넣은 후, answer 배열에 하나씩 다시 담았습니다.
> [김세민] 240731 풀이 제출

- week9/leetcode/1653-minimum-deletions-to-make-string-balanced/rglley.java
- week9/programmers/118669-등산코스-정하기/rglley.java
> Runtime: 24ms
> Memory: 45.1MB
dp로 b 개수를 카운팅하고, a를 만났을 때 이전의 b들을 지울지, a를 지울지 판별했습니다.
---
> Runtime: 2138.61ms
> Memory: 152MB
summit 정렬을 안해서 헤맸네요.
다익스트라로 풀이했습니다.
> [이경배] 240730 풀이 제출

- week9/leetcode/1653-minimum-deletions-to-make-string-balanced/itsmo1031.java
- week9/programmers/118669-등산코스-정하기/itsmo1031.java
> Runtime: 21ms
> Memory: 45.27MB
왼쪽부터 b의 개수를 세어가면서 a를 지울지, b를 지울지를 결정했습니다.
---
> Runtime: 1508.35ms
> Memory: 499MB
다익스트라를 활용하여 풀이했는데, 생각보다 메모리와 런타임이 많이 나오네요. 조금 더 나은 방식이 있을 것 같습니다.
> [정필모] 20240730 풀이 제출

- week9/leetcode/1105-filling-bookcase-shelves/rglley.java
- week9/programmers/68645-삼각-달팽이/rglley.java
> Runtime: 1ms
> Memory: 41.9MB
dp를 활용해 어떤 책을 넣어야 최소 높이가 되는지 판별했습니다. 
---
> Runtime: 21.72ms
> Memory: 146MB
임시 2차원 배열에 층마다 위 || 아래 || 오른쪽으로 숫자를 채워넣는 패턴을 찾아 풀이했습니다.
> [이경배] 240731 풀이 제출

- week9/leetcode/1105-filling-bookcase-shelves/itsmo1031.java
- week9/programmers/68645-삼각-달팽이/itsmo1031.java
> Runtime: 1ms
> Memory: 41.84MB
DP임은 짐작했는데 딱 거기까지였네요. 뚜렷한 방법이 생각나지 않아서 고전했습니다.
---
> Runtime: 20.02ms
> Memory: 137MB
while문을 활용해 돌려가며 계산했는데, 생각해보니 for문 두개로 충분할 것 같네요. 다시 푼다면 for문을 활용해서 풀이할 것 같습니다.
> [정필모] 240731 풀이 제출

- week9/leetcode/2678-number-of-senior-citizens/rglley.java
- week9/programmers/12920-선입-선출-스케줄링/rglley.java
> Runtime: 1ms
> Memory: 42.3MB
이러면 안되겠지만, Easy만 보면 미소가 지어지네요
---
> Runtime: 4.76ms
> Memory: 52.6MB
이분탐색은 바로 캐치했는데, 완성된 작업, 진행중인 작업 기준이 헷갈려서 헤맸습니다.
이분탐색으로 진행 작업이 n을 넘기는 시간을 찾고, 완성된 작업이 n이 되는 코어를 찾아 풀이했습니다.
> [이경배] 240801 풀이 제출

- week9/leetcode/2678-number-of-senior-citizens/itsmo1031.java
- week9/programmers/12920-선입-선출-스케줄링/itsmo1031.java
> Runtime: 1ms
> Memory: 42.74MB
String의 substring을 활용했습니다.
---
> Runtime: 5.49ms
> Memory: 52.4MB
처음에 PriorityQueue로 접근했다가 효율성이 박살이 났어요. 이후 이분 탐색 문제 같다는 생각은 했는데 어떻게 활용해야 할 지 감이 전혀 안 왔습니다. 이분 탐색 관련 문제를 많이 풀어봐야 할 것 같아요.
> [정필모] 240801 풀이 제출

- week9/leetcode/2134-minimum-swaps-to-group-all-1s-together-ii/rglley.java
- week9/programmers/118667-두-큐-합-같게-만들기/rglley.java
> Runtime: 9ms
> Memory: 59.29MB
영 감을 못잡다가 힌트를 참고해서 슬라이딩 윈도우로 풀이했습니다.
전체 1의 개수를 구하고, 윈도우 별 1의 최대 개수를 갱신해 swap 수를 계산했습니다.
---
> Runtime: 123.29ms
> Memory: 152MB
두 큐의 합이 같아질 때 까지 합이 더 큰 큐에서 작은 큐로 숫자를 넣어 풀이했습니다.
> [이경배] 240802 풀이 제출

- week10/leetcode/2053-kth-distinct-string-in-an-array/itsmo1031.java
- week10/programmers/148653-마법의-엘리베이터/itsmo1031.java
> Runtime: 6ms
> Memory: 44.10MB
HashMap을 사용해서 풀었는데, 맵 안쓰고 일반 배열로 풀이했어도 됐을 것 같네요.
---
> Runtime: 2.04ms
> Memory: 81.7MB
While문 단일로 풀려다가 생각하기 귀찮아서 bfs 돌렸습니다. 현재 자릿수 말고 그 윗 자리수까지 같이 고려해서 풀었다면 while문 단일로도 풀렸겠네요.
> [정필모] 240805 풀이 제출

- week10/leetcode/2053-kth-distinct-string-in-an-array/kimgiraffe.java
- week10/programmers/148653-마법의-엘리베이터/kimgiraffe.java
> Runtime: 6ms
> Memory: 44.3MB
map 자료구조를 이용하여 풀었습니다.
---
> Runtime: 0.03ms
> Memory: 74.8MB
층을 10으로 나눈 나머지에 대하여 5보다 큰 경우에는 + 버튼, 5보다 작은 경우에는 - 버튼, 5인 경우에는 앞자리를 기준으로 비교했습니다.
> [김세민] 240805 풀이 제출

- week10/leetcode/2053-kth-distinct-string-in-an-array/rglley.java
- week10/programmers/148653-마법의-엘리베이터/rglley.java
> Runtime: 6ms
> Memory: 47.73MB
개수를 Map에 카운팅하고, entrySet으로 k번째 수를 찾 풀이했습니다.
---
> Runtime: 0.03ms
> Memory: 90.3MB
끝의 두자리 수를 고려해 풀이했습니다.
끝 자리수가 5보다 작은 경우 아래층으로, 5인 경우 다음 자릿수가 5 이상이면 윗 층으로, 5보다 크면 윗층으로 이동했습니다.
> [이경배] 240805 풀이 제출

- week10/leetcode/3016-minimum-number-of-pushes-to-type-word-ii/rglley.java
- week10/programmers/60063-블록-이동하기/rglley.java
> Runtime: 7ms
> Memory: 46.03MB
알파벳 수를 카운팅해, 많은 순서대로 버튼에 할당해 풀이했습니다.
---
> Runtime: 13.12ms
> Memory: 86.7MB
로봇의 가로, 세로 상태에 따라 vistied 배열을 구분하고,
회전, 이동이 가능한지를 판별해 풀이했습니다.
> [이경배] 240806 풀이 제출

- week10/leetcode/3016-minimum-number-of-pushes-to-type-word-ii/itsmo1031.java
- week10/programmers/60063-블록-이동하기/itsmo1031.java
> Runtime: 8ms
> Memory: 45.21MB
각 알파벳별 freq를 재고, freq가 많은 순서대로 우선 배정하도록 했습니다.
---
> Runtime: 47.73ms
> Memory: 132MB
BFS를 이용했는데, 이동 가능한 포지션을 세는 로직을 조금 더 개선할 수 있을 것 같네요. 클래스를 써서 오히려 더 복잡해진 느낌입니다. (equals 재정의 등)
> [정필모] 240806 풀이 제출

- week10/leetcode/273-integer-to-english-words/itsmo1031.java
- week10/programmers/72411-메뉴-리뉴얼/itsmo1031.java
> Runtime: 5ms
> Memory: 42.17MB
1단위 숫자, 10단위 숫자, 단어가 바뀌는 11~19를 map에 개별로 저장해두고 세자리마다 끊어서 해싱했습니다. 공백 처리가 살짝 까다로웠는데, 하드까진 아닌 것 같아요.
---
> Runtime: 28.29ms
> Memory: 89.4MB
조합을 이용해서 경우의 수를 뽑아 저장한 후, 최댓값을 산출해서 이를 정답 리스트에 담았습니다. stream 사용이 깔끔할 것 같아 공부 겸 활용했는데, 실전이었다면 그냥 for문 굴려가면서 구했을 것 같네요.
> [정필모] 240807 풀이 제출

- week10/leetcode/273-integer-to-english-words/rglley.java
- week10/programmers/72411-메뉴-리뉴얼/rglley.java
> Runtime: 1ms
> Memory: 41.68MB
20까지 배열에 담아주고, 10마다 배열에 담아주고,
재귀 호출로 100, 1000, 십만, 십억 단위로 끊어 StringBuilder에 더해줬습니다.
---
> Runtime: 26.45ms
> Memory: 84.5MB
dfs로 빈도수를 확인하고 hashmap에 결과값을 저장해 풀이했습니다.
> [이경배] 240807 풀이 제출
